#!/bin/sh
#
#  check-zzuf-s-seed - zzuf seed efficiency statistic tests
#  Copyright (c) 2008-2010 Sam Hocevar <sam@hocevar.net>
#                All Rights Reserved
#
#  This program is free software. It comes without any warranty, to
#  the extent permitted by applicable law. You can redistribute it
#  and/or modify it under the terms of the Do What The Fuck You Want
#  To Public License, Version 2, as published by Sam Hocevar. See
#  http://sam.zoy.org/wtfpl/COPYING for more details.
#

. "$(dirname "$0")/functions.inc"

start_test "zzuf -s test"

for ratio in 1 0.1 0.01 0.001 0.0001; do
  if test $ratio = 0.0001; then
    bytes=1024
  elif test $ratio = 0.001; then
    bytes=8192
  else
    bytes=32768
  fi
  new_test "$bytes B of zeroes, ratio $ratio"
  zeroes=$(expr $bytes '*' 4)
  passes=10
  while test $zeroes -gt 0 -a $passes -lt 200000; do
    printf " doing $passes passes..."
    zeroes=$($ZZUF -r $ratio -s $seed -A $ZZCAT -r $passes -x "fread(1,$bytes)" /dev/zero | $DIR/zzone $bytes $passes)
    echo " $zeroes"
    passes=$(expr '(' $passes '*' 7 + 3 ')' / 4)
  done
  if test $passes -lt 2000000; then
      pass_test " ok"
  else
      pass_test " FAILED"
  fi
done

stop_test

