#!/bin/sh

. "$(dirname "$0")/functions.inc"

checkflip()
{
    r=$1
    expect=$2
    s2=$seed
    mib=20
    rmax=-1
    rmin=-1
    rtot=0
    new_test "$mib MiB of zeroes, ratio $r"
    for x in 0 1 2 3 4; do
        ret=`dd if=/dev/zero bs=1048576 count=$mib 2>/dev/null | $ZZUF -s $s2 -r $r | "$ZZERO"`
        if [ "$rmax" = -1 -o "$ret" -gt "$rmax" ]; then rmax=$ret; fi
        if [ "$rmin" = -1 -o "$ret" -lt "$rmin" ]; then rmin=$ret; fi
        rtot=`expr $rtot + $ret || true`
        echo " try $x .......... $ret"
        s2=`expr $s2 + 1`
    done
    rmean=`expr '(' $rtot + 2 ')' / 5 || true`
    delta=`expr $rmean - $expect || true`
    printf " expected $expect min/avg/max $rmin/$rmean/$rmax .........."
    if [ "$delta" -gt -5 -a "$delta" -lt 5 ]; then
        pass_test " ok"
    elif [ $(($rmean * 8)) -lt $(($expect * 7)) \
               -o $(($rmean * 7)) -gt $(($expect * 8)) ]; then
        fail_test " FAILED"
    else
        pass_test " ok"
    fi
}

start_test "zzuf RNG test suite"

# if X flips are performed on N bits set to 0, the average number of bits
# set to 1 is: N / 2 * (1 - pow(1 - 2 / N, X)
checkflip 0.000000001 0
checkflip 0.00000001  1
checkflip 0.0000001  16
checkflip 0.000001  167
checkflip 0.00001  1677
checkflip 0.0001  16775
checkflip 0.001  167604
checkflip 0.01  1661055
checkflip 0.1  15205967

stop_test

