#! /bin/sh

##  Win32 cross-compilation for zzuf -- Sam Hocevar <sam@zoy.org>
##  $Id$

set -x
set -e

# Clean up our working directory
SRCDIR="`pwd`"
DIRNAME="zzuf-win32-`sed -ne 's/^AM_INIT_AUTOMAKE(.*, \(.*\)).*/\1/p' configure.ac`"
INSTALLDIR="`pwd`/${DIRNAME}"
BUILDDIR="${INSTALLDIR}/build"
rm -Rf "${INSTALLDIR}"
rm -f "${INSTALLDIR}.zip"
mkdir "${INSTALLDIR}"
mkdir "${BUILDDIR}"

cd "${BUILDDIR}"
# Build for win32
"${SRCDIR}/configure" --host=i586-mingw32msvc --prefix=/ --bindir=/bin --libdir=/lib

make pkglibdir=/lib pkgdatadir=/data bindir=/bin

make install DESTDIR="${INSTALLDIR}" pkglibdir=/lib/ pkgdatadir=/ bindir=/bin/
rm -Rf "${BUILDDIR}"

# Pack the directory
cd "${SRCDIR}"
zip "${DIRNAME}.zip" `find "${DIRNAME}"`
rm -Rf "${INSTALLDIR}"

